### ISSUE TITLE
Response hang when using async callback 

### ISSUE THREAD

**Issue by lubinson** [nhenneaux/jaxrs-http2-example#1]
Hi Author,

I am recently trying to use JettyHttp2Connector in Jersey to process HTTP2 message.
I am using JAX-RS code to send HTTP2 request sync, async and async callback.
The sync and async is ok. But async callback can't work. 
The receive code is hang at the response.readEntity(...). But actually the response.getStatus is ok.

My code is like below:

```
        Future<Response> responseFuture = target.request().async().post(Entity.entity(json, MediaType.APPLICATION_JSON), new InvocationCallback<Response>() {
          @Override
          public void completed(Response response) {
              System.out.println("Response status code "  + response.getStatus() + " received.");
              System.out.println(response.hasEntity());
              System.out.println("here");
              ...
              
          }
     
          @Override
          public void failed(Throwable throwable) {
              System.out.println("Invocation failed.");
             throwable.printStackTrace();
          }
      });
```

above code stop at  System.out.println(response.hasEntity());

I am not sure it is an issue, but it looks have something not right either in my usage or underlay code. 
Could you help to look at this. Thanks.

**Comment by nhenneaux** [comment]
Hi,

Your code is working using the HTTP 1.1 connector of Jetty? Have you checked what is sent between the server and client (you can enable debug mode of Jetty for those information)?

**Comment by lubinson** [comment]
Thanks for your quick response:)

I have checked with pcap and it is sent with HTTP2 very effective. All the responses are sent back to the client. But above just print result code 200, didn't continue to print response content. 

Best Regards.

**Comment by lubinson** [comment]
I have added a system print in below code in JettyHttp2Connector.java.
```
    private static class ClientResponseFutureCallback implements FutureCallback<ClientResponse> {
        private final Request jettyRequest;

        ClientResponseFutureCallback(Request jettyRequest) {
            this.jettyRequest = jettyRequest;
            System.out.println("bbbbbbbbbb");
        }

        @Override
        public void onSuccess(final ClientResponse result) {
            // Nothing to do
          System.out.println("aaaaaaaaaaa");
        }

        @Override
        public void onFailure(final Throwable t) {
            if (t instanceof CancellationException) {
                // take care of future cancellation
                jettyRequest.abort(t);
            }
        }
    }
```

When I use sync or async call, the onSuccess() is called. But when I use async callback, the onSuccess() is not called. 

The async call code is just the same as sample code in JettyHttp2Connector.java. 

Best Regards.

**Comment by lubinson** [comment]
Update:

When I change    
the method public Future<?> apply(final ClientRequest jerseyRequest, final AsyncConnectorCallback callback) in JettyHttp2Connector.java to the same method in JettyConnector.java. It works.

**Comment by nhenneaux** [comment]
It seems you have spotted a bug could you submit a PR with your changes?

**Comment by lubinson** [comment]
Sorry, I just replace the code to see whether it can work, Actually I am not familiar with the replaced code:)

**Comment by nhenneaux** [comment]
I reverted some changes in the code. Could you try again ?

**Comment by lubinson** [comment]
ok, I will try and back to you several days later.

**Comment by lubinson** [comment]
Just tried, can't got the responses but actually the server has already sent back responses.

**Comment by nhenneaux** [comment]
@lubinson does it mean you still have the problem or not?

**Comment by lubinson** [comment]
I am not in the project.
If the code is not changed, I think the issue is still there.

On Thu, Nov 30, 2017 at 10:36 PM, Nicolas Henneaux <notifications@github.com

**Comment by nhenneaux** [comment]
I have just updated to latest Jetty and Jersey version with some fix in the connector. Could you test again?

**Comment by lubinson** [comment]
Sorry, I didn't have chance to do so.

**Comment by nhenneaux** [comment]
I close unless you reproduce the problem. It would be useful to have a test case to reproduce if you manage to.
