### ISSUE TITLE
not able to build - to find org.eclipse.jetty:jetty-alpn-java-client:jar:9.4.1.v20170120 

### ISSUE THREAD

**Issue by pkapildas** [nhenneaux/jaxrs-http2-example#2]
INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 33.785 s
[INFO] Finished at: 2017-11-30T18:49:44+05:30
[INFO] Final Memory: 11M/39M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project jaxrs-http2-example: Could not resolve dependencies for project nhenneaux:jaxrs-http2-example:jar:1.0-SNAPSHOT: Failure to find org.eclipse.jetty:jetty-alpn-java-client:jar:9.4.1.v20170120 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 

after checking the maven repo 
to find org.eclipse.jetty:jetty-alpn-java-client:jar:9.4.1.v20170120  is build  for Jdk 9 - and with jdk8 this getting failed, i didn't tried in Jdk 9

**Comment by nhenneaux** [comment]
Hi,
I have already reported this issue to the GitHub of Jetty ALPN. I am waiting for a fix :-(
https://github.com/jetty-project/jetty-alpn/issues/15
